"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 翻译字典
const translations = {
  zh: {
    // 通用
    "common.loading": "加载中...",
    "common.search": "搜索",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.create": "创建",
    "common.confirm": "确认",
    "common.back": "返回",
    "common.next": "下一步",
    "common.previous": "上一步",
    "common.submit": "提交",
    "common.close": "关闭",
    "common.view": "查看",
    "common.manage": "管理",
    "common.settings": "设置",
    "common.status": "状态",
    "common.active": "活跃",
    "common.inactive": "非活跃",
    "common.online": "在线",
    "common.offline": "离线",
    "common.connected": "已连接",
    "common.disconnected": "未连接",
    "common.error": "错误",
    "common.success": "成功",
    "common.warning": "警告",
    "common.info": "信息",
    "common.changes": "更改",
    "common.operation": "操作",

    // 系统标题
    "system.title": "ChatX",
    "system.subtitle": "SaaS v1.0.0",
    "system.welcome": "欢迎回来",

    // 导航菜单
    "nav.dashboard": "仪表盘",
    "nav.customer_service": "客服系统",
    "nav.all_chats": "所有聊天",
    "nav.account_management": "账户管理",
    "nav.data_reports": "数据报表",
    "nav.kpi": "客服 KPI",
    "nav.chat_report": "聊天报表",
    "nav.system_management": "系统管理",
    "nav.permissions_management": "权限管理",
    "nav.workspaces_management": "工作空间管理",
    "nav.plans_management": "配套配置",

    // 配套管理
    "plans.title": "配套管理",
    "plans.create": "创建配套",
    "plans.total_plans": "总配套数",
    "plans.active_plans": "活跃配套",
    "plans.total_subscribers": "总订阅用户",
    "plans.total_revenue": "总收入",
    "plans.search_placeholder": "搜索...",
    "plans.list_title": "配套列表",
    "plans.disabled": "已禁用",
    "plans.max_workspace": "最大工作空间",
    "plans.max_account": "最大账号数",
    "plans.price": "价格",
    "plans.billing_cycle": "计费周期",
    "plans.monthly": "月付",
    "plans.quarterly": "季付",
    "plans.yearly": "年付",
    "plans.plan_name": "配套名称",
    "plans.plan_description": "描述",
    "plans.enter_plan_name": "输入配套名称...",
    "plans.enter_plan_description": "输入配套描述...",
    "plans.enter_plan_price": "输入配套价格",
    "plans.max_workspaces_unlimited": "最大工作空间（0=无限）",
    "plans.max_accounts_unlimited": "最大账号数（0=无限）",
    "plans.cancel": "取消",
    "plans.add": "添加",
    "plans.save": "保存",
    "plans.confirm_edit_title": "确认修改",
    "plans.confirm_edit_message": "您确定要保存对此配套的更改吗？",
    "plans.confirm_delete_title": "确认操作",
    "plans.confirm_delete_message": "您确定要删除这个配套吗？",
    "plans.confirm": "确认",
    "plans.edit": "编辑",
    "plans.delete": "删除",
    "plans.plan_created_success": "配套创建成功",
    "plans.plan_created_success_desc": "新配套已成功创建。",
    "plans.plan_updated_success": "配套更新成功",
    "plans.plan_updated_success_desc": "配套已成功更新。",
    "plans.plan_deleted_success": "配套删除成功",
    "plans.plan_deleted_success_desc": "配套已成功删除。",
    "plans.missing_id_error": "缺少ID字段。",
    "plans.missing_id_error_desc": "无法在没有ID的情况下更新配套。",
    "plans.permission_denied": "权限不足",
    "plans.permission_denied_desc": "您没有权限访问此页面",

    // Tooltip 提示
    "tooltip.add_account": "添加账号",
    "tooltip.language_toggle": "切换语言",
    "tooltip.theme_toggle": "切换主题",
    "tooltip.time_settings": "时间设置",
    "tooltip.user_menu": "用户菜单",

    // 语音录制相关
    "voice.recording": "正在录制...",
    "voice.stop_recording": "停止录制",
    "voice.recording_completed": "语音录制完成",
    "voice.delete": "删除",
    "voice.send": "发送",
    "voice.record_voice": "录制语音",
    "voice.voice_message": "语音消息",
    "voice.recording_failed": "录制失败",
    "voice.send_failed": "发送失败",
    "voice.sending": "发送中...",

    // 附件菜单相关
    "attachment.sticker": "贴纸",
    "attachment.document": "文档",
    "attachment.photo_video": "照片和视频",
    "attachment.loading_failed": "加载失败",

    // 输入框相关
    "input.placeholder": "输入消息...",
    "input.send": "发送",
    "input.type_message": "输入消息...",

    // 系统相关
    "common.system": "系统",
    "common.uploading": "上传中...",
    "common.converting": "转换中...",
    "common.sending": "发送中...",
    "common.send_failed": "发送失败",
    "common.upload_failed": "上传失败",
    "common.document": "文档",
    "common.photo": "照片",
    "common.video": "视频",
    "common.voice_message": "语音消息",
    "common.preparing_playback": "准备播放...",
    "common.downloading": "下载中...",
    "common.loading_failed": "加载失败",

    // 聊天相关
    "chat.send_failed_retry": "消息发送失败，请重试",

    // 测试相关
    "test.connection_test": "连接测试",
    "test.current_status": "当前状态",
    "test.test_click": "测试点击事件",
    "test.test_api_connection": "测试API连接",
    "test.open_console_for_logs": "请打开控制台查看日志输出",

    // 登录页面
    "login.title": "Chat-X",
    "login.subtitle": "登录您的账户以访问客服管理平台",
    "login.email": "邮箱地址",
    "login.password": "密码",
    "login.email_placeholder": "请输入您的邮箱",
    "login.password_placeholder": "请输入您的密码",
    "login.button": "登录",
    "login.logging_in": "登录中...",
    "login.demo_accounts": "演示账号：",
    "login.admin_account": "管理员：admin@example.com / admin123",
    "login.manager_account": "经理：manager@example.com / manager123",
    "login.agent_account": "客服：agent@example.com / agent123",
    "login.error_empty": "请输入邮箱和密码",
    "login.error_invalid": "邮箱或密码错误，请重试",
    "login.or_separator": "或",

    // 仪表盘
    "dashboard.title": "仪表盘",
    "dashboard.plan_id": "配套",
    "dashboard.accounts": "账号数量",
    "dashboard.workspaces": "工作空间数量",
    "dashboard.today_conversations": "今日对话",
    "dashboard.active_users": "活跃用户",
    "dashboard.ai_processing_rate": "AI 处理率",
    "dashboard.avg_response_time": "平均响应",
    "dashboard.ai_effectiveness": "AI 处理效果",
    "dashboard.auto_reply_success": "自动回复成功率",
    "dashboard.customer_satisfaction": "客户满意度",
    "dashboard.problem_resolution": "问题解决率",
    "dashboard.transfer_to_human": "转人工率",
    "dashboard.recent_activities": "最近活动",
    "dashboard.quick_actions": "快速操作",
    "dashboard.view_conversations": "查看对话",
    "dashboard.user_management": "用户管理",
    "dashboard.data_reports": "数据报表",
    "dashboard.ai_settings": "AI 设置",
    "dashboard.welcome_back": "欢迎回来",
    "dashboard.view_reports": "查看报表",
    "dashboard.start_conversation": "开始对话",
    "dashboard.compared_yesterday": "较昨日",
    "dashboard.minutes": "分钟",
    "dashboard.auto_reply_success_rate": "自动回复成功率",
    "dashboard.customer_satisfaction_rate": "客户满意度",
    "dashboard.problem_resolution_rate": "问题解决率",
    "dashboard.transfer_to_human_rate": "转人工率",
    "dashboard.new_customer_conversation": "新客户张小明发起对话",
    "dashboard.ai_handled_technical": "AI 成功处理技术咨询问题",
    "dashboard.service_timeout_reminder": "客服回复超时提醒",
    "dashboard.new_user_registration": "新用户注册：john@example.com",
    "dashboard.minutes_ago": "分钟前",
    "dashboard.view_conversations_action": "查看对话",
    "dashboard.user_management_action": "用户管理",
    "dashboard.data_reports_action": "数据报表",
    "dashboard.ai_settings_action": "AI 设置",

    // 用户菜单
    "user.profile": "个人资料",
    "user.account_settings": "账户设置",
    "user.logout": "退出登录",
    "user.role.superadmin": "管理员",
    "user.role.manager": "经理",
    "user.role.supervisor": "监督员",
    "user.role.agent": "客服",
    "profile.role_readonly_description": "角色由管理员分配，无法修改",

    // 权限相关
    "permission.insufficient": "权限不足",
    "permission.no_access": "您没有权限访问此页面",
    "permission.no_access_feature": "您没有权限访问此功能",

    // 权限分类翻译
    "permissions.category.User Management": "用户管理",
    "permissions.category.Customer Management": "客服管理",
    "permissions.category.System Management": "系统管理",
    "permissions.category.Workspace Management": "工作空间管理",

    // 具体权限翻译
    "permissions.user.create": "创建用户",
    "permissions.user.edit": "编辑用户",
    "permissions.user.delete": "删除用户",
    "permissions.user.view": "查看用户",
    "permissions.chat.manage": "管理聊天",
    "permissions.chat.view": "查看聊天",
    "permissions.chat.reply": "回复聊天",
    "permissions.chat.assign": "分配聊天",
    "permissions.account.manage": "管理账户",
    "permissions.plan.manage": "管理配套",
    "permissions.workspace.manage": "管理工作空间",
    "permissions.workspace.view": "查看工作空间",

    // 客服系统
    "service.title": "客服系统",
    "service.subtitle": "处理客户对话和服务请求",
    "service.filter": "筛选",
    "service.reply_immediately": "立即回复",
    "service.pending_conversations_count": "待处理对话",
    "service.status_waiting": "等待中",
    "service.ai_suggestions_title": "AI 转接建议",
    "service.technical_detected": "检测到技术问题对话",
    "service.view_details_btn": "查看详情",
    "service.view_report_btn": "查看报告",
    "service.search_customer": "搜索客户或对话...",

    // 营销工具
    "marketing.title": "营销工具",
    "marketing.subtitle": "批量消息发送和营销活动管理",
    "marketing.today_sent": "今日发送",
    "marketing.reached_users": "触达用户",
    "marketing.reply_rate": "回复率",
    "marketing.conversion_rate": "转化率",
    "marketing.bulk_message": "批量消息",
    "marketing.bulk_description": "向多个用户发送相同消息",
    "marketing.create_bulk": "创建批量消息",
    "marketing.scheduled_send": "定时发送",
    "marketing.scheduled_description": "设置消息发送时间",
    "marketing.set_schedule": "设置定时",
    "marketing.customer_groups": "客户分组",
    "marketing.groups_description": "管理客户分组和标签",
    "marketing.manage_groups": "管理分组",
    "marketing.ongoing_activities": "进行中的活动",
    "marketing.in_progress": "进行中",
    "marketing.paused": "已暂停",
    "marketing.send_progress": "发送进度",
    "marketing.start_time": "开始时间",
    "marketing.estimated_completion": "预计完成",
    "marketing.hours_later": "小时后",
    "marketing.member_recruitment": "会员招募",
    "marketing.send_statistics": "发送统计",
    "marketing.interaction_data": "互动数据",
    "marketing.open_rate": "打开率",
    "marketing.click_rate": "点击率",

    // 账户管理
    "account.title": "账户管理",
    "account.subtitle": "管理 WhatsApp 和 Telegram 账号连接",
    "account.total_accounts": "总账号数",
    "account.connected": "已连接",
    "account.active_accounts": "活跃账号",
    "account.today_messages": "今日消息",
    "account.add_account": "添加账号",
    "account.whatsapp_accounts": "WhatsApp 账号",
    "account.telegram_accounts": "Telegram 账号",
    "account.no_whatsapp": "暂无 WhatsApp 账号",
    "account.no_telegram": "暂无 Telegram 账号",
    "account.add_whatsapp": "添加 WhatsApp 账号",
    "account.add_telegram": "添加 Telegram 账号",
    "account.search_placeholder": "搜索账号名称、手机号或用户名...",
    "account.expand_all": "全部展开",
    "account.collapse_all": "全部收起",
    "account.account_count": "个账号",
    "account.last_active": "最后活跃",
    "account.messages": "消息",
    "account.connection_normal": "连接正常",
    "account.connection_error": "连接异常",
    "account.not_connected": "未连接",
    "account.status_connected": "已连接",
    "account.status_disconnected": "未连接",
    "account.status_error": "连接错误",
    "account.insufficient_permission": "权限不足",
    "account.no_permission_message": "您没有权限访问账户管理功能",
    "account.loading_failed": "加载账号数据失败",
    "account.delete_failed": "删除账号失败",
    "account.deleted": "账号已删除",
    "account.delete_success": "账号删除成功",
    "account.deleting": "正在删除...",
    "account.deleting_description": "正在删除账号，请稍候",
    "account.toggle_failed": "切换账号状态失败",
    "account.just_now": "刚刚",
    "account.minutes_ago": "分钟前",
    "account.hours_ago": "小时前",
    "account.days_ago": "天前",

    // 工作空间管理
    "workspace.title": "工作空间管理",
    "workspace.total_workspace": "总工作空间",
    "workspace.total_brand": "总品牌数",
    "workspace.total_supervisor": "总监督员",
    "workspace.total_agent": "总客服员",
    "workspace.create_workspace": "创建工作空间",
    "workspace.search_placeholder": "搜索...",
    "workspace.workspace_list": "工作空间列表",
    "workspace.workspace_name": "工作空间名称",
    "workspace.description": "描述",
    "workspace.brands": "品牌",
    "workspace.team_members": "团队成员",
    "workspace.no_description": "暂无描述",
    "workspace.no_brands": "暂无品牌",
    "workspace.no_members": "暂无团队成员",
    "workspace.members_count": "团队成员",
    "workspace.created_by": "创建者",
    "workspace.edit": "编辑",
    "workspace.delete": "删除",
    "workspace.save": "保存",
    "workspace.cancel": "取消",
    "workspace.add": "添加",
    "workspace.confirm_delete": "确认删除",
    "workspace.confirm_edit": "确认编辑",
    "workspace.delete_warning": "您确定要删除这个工作空间吗？此操作不可撤销。",
    "workspace.edit_warning": "您确定要编辑这个工作空间吗？此操作不可撤销。",
    "workspace.create_new_brand": "创建新品牌",
    "workspace.edit_brand": "编辑品牌",
    "workspace.brand_name": "品牌名称",
    "workspace.enter_brand_name": "输入品牌名称...",
    "workspace.create": "创建",
    "workspace.add_team_member": "添加团队成员",
    "workspace.select_subordinate": "选择下属",
    "workspace.choose_user": "选择用户",
    "workspace.no_supervisors": "暂无监督员",
    "workspace.no_agents": "暂无客服员",
    "workspace.select_supervisor": "选择监督员",
    "workspace.select_agent": "选择客服员",
    "workspace.select_members": "选择成员",
    "workspace.display_name": "显示名称",
    "workspace.enter_workspace_name": "输入工作空间名称...",
    "workspace.enter_workspace_description": "输入工作空间描述...",

    // 添加账号对话框
    "dialog.add_account": "添加新账号",
    "dialog.platform_type": "平台类型",
    "dialog.display_name": "显示名称",
    "dialog.description": "描述",
    "dialog.connection_settings": "连接设置",
    "dialog.please_select_connection": "请选择连接方式",
    "dialog.generate_qr": "生成二维码",
    "dialog.phone_login": "手机号登录",
    "dialog.qr_login": "扫码登录", 
    "dialog.use_phone": "使用手机号登录",
    "dialog.use_qr": "使用二维码登录",
    "dialog.scan_qr": "扫描二维码连接",
    "dialog.scan_with_app": "请使用 WhatsApp 手机应用扫描二维码",
    "dialog.scan_with_telegram": "请使用 Telegram 手机应用扫描二维码",
    "dialog.connection_success": "连接成功！",
    "dialog.click_add_to_complete": "点击添加按钮完成账号绑定",
    "dialog.phone_number": "手机号码",
    "dialog.phone_placeholder": "+86 138****8888",
    "dialog.send_code": "发送验证码",
    "dialog.sending": "发送中...",
    "dialog.verification_code": "验证码",
    "dialog.code_placeholder": "输入验证码",
    "dialog.code_sent_to": "验证码已发送至",
    "dialog.resend": "重新发送",
    "dialog.verify": "验证",
    "dialog.verifying": "验证中...",
    "dialog.two_fa_password": "两步验证密码",
    "dialog.two_fa_placeholder": "输入两步验证密码",
    "dialog.two_fa_required": "需要两步验证密码来完成登录",
    "dialog.restart": "重新开始",
    "dialog.verify_password": "验证密码",
    "dialog.password_verifying": "验证中...",
    "dialog.add": "添加",
    "dialog.cancel": "取消",
    "dialog.connecting": "连接中",
    "dialog.loading": "正在加载",
    "dialog.waiting_scan": "等待扫描二维码",
    "dialog.connection_failed": "连接失败",
    "dialog.generate_qr_failed": "生成二维码失败",
    "dialog.regenerate": "重新生成",
    "dialog.retry": "重试",

    // Toast 通知
    "toast.connection_success": "连接成功",
    "toast.telegram_connected": "Telegram 账号连接成功！",
    "toast.whatsapp_connected": "WhatsApp 账号连接成功！",
    "toast.account_added": "账号添加成功",
    "toast.telegram_added": "Telegram 账号添加成功！",
    "toast.whatsapp_added": "WhatsApp 账号添加成功！",
    "toast.input_error": "输入错误",
    "toast.phone_required": "请输入手机号码",
    "toast.code_required": "请输入验证码",
    "toast.password_required": "请输入两步验证密码",
    "toast.system_error": "系统错误",
    "toast.missing_tx_id": "缺少事务ID",
    "toast.send_failed": "发送失败",
    "toast.code_send_failed": "发送验证码失败",
    "toast.verify_failed": "验证失败",
    "toast.verification_failed": "验证失败",
    "toast.password_invalid": "两步验证密码错误，请重新输入",
    "toast.save_failed": "保存失败",
    "toast.generate_failed": "生成失败",
    "toast.qr_generate_failed": "生成二维码失败",
    "toast.two_fa_required": "需要两步验证",
    "toast.two_fa_prompt": "请输入您的两步验证密码",
    "toast.signup_required": "账号需要注册",
    "toast.signup_prompt": "此手机号需要先在Telegram官方应用中注册账号",
    "toast.missing_field": "登录成功但有警告",
    "toast.missing_prompt": "Workspace 或 Brand 未选择，请稍后在设置中补全",

    // 账号操作
    "account.delete_confirm_title": "确认删除账号",
    "account.delete_confirm_message": "确定要删除这个账号吗？此操作不可撤销。",
    "account.delete_confirm": "确认删除",
    "account.edit_account": "编辑账号",
    "account.refresh_connection": "刷新连接",
    "account.expand_description": "展开描述",
    "account.collapse_description": "收起描述",

    // 权限管理
    "permissions.title": "权限管理",
    "permissions.subtitle": "管理用户账号、角色和权限",
    "permissions.create_user": "创建用户",
    "permissions.total_users": "总用户数",
    "permissions.active_users": "活跃用户",
    "permissions.total_roles": "角色数量",
    "permissions.permission_items": "权限项",
    "permissions.user_management": "用户管理",
    "permissions.role_management": "角色管理",
    "permissions.search_placeholder": "搜索用户名或邮箱...",
    "permissions.all_roles": "所有角色",
    "permissions.user_list": "用户列表",
    "permissions.current_user": "当前用户",
    "permissions.disabled": "已禁用",
    "permissions.department": "部门",
    "permissions.department_placeholder": "输入部门...",
    "permissions.created": "创建",
    "permissions.last_login": "最后登录",
    "permissions.last_connected": "最后连接",
    "permissions.never_login": "从未登录",
    "permissions.all_permissions": "所有权限",
    "permissions.permissions_count": "项权限",
    "permissions.name": "姓名",
    "permissions.email": "邮箱",
    "permissions.role": "角色",
    "permissions.merchant": "商户",
    "permissions.plan": "配套",
    "permissions.password": "密码",
    "permissions.manager": "经理",
    "permissions.reset_password": "重置密码",
    "permissions.enter_user_name": "输入用户姓名",
    "permissions.enter_email": "输入邮箱地址",
    "permissions.enter_new_password": "输入新密码",
    "permissions.no_managers_available": "没有可用的经理",
    "permissions.role_name": "角色名称",
    "permissions.role_identifier": "角色标识", 
    "permissions.role_description": "角色描述",
    "permissions.enter_role_name": "输入角色名称",
    "permissions.enter_role_description": "输入角色描述",
    "permissions.select_role": "选择角色",
    "permissions.role_list": "角色列表",
    "permissions.users_count": "用户",
    "permissions.permissions_count_label": "权限数量:",
    "permissions.users_count_label": "用户数量:",
    "permissions.edit": "编辑",
    "permissions.permissions": "权限",
    "permissions.permissions_configuration": "权限配置",
    "permissions.save": "保存",
    "permissions.confirm_save_changes": "您确定要保存对",
    "permissions.confirm_update_permissions": "您确定要更新这个角色的权限吗？",
    "permissions.confirm_create_new_role": "您确定要创建一个新角色吗？",
    "permissions.confirm_update_role": "您确定要更新这个角色吗？",
    "permissions.confirm_delete_user": "确认删除用户",
    "permissions.confirm_delete_user_message": "您确定要删除用户",
    "permissions.confirm_delete_user_warning": "此操作不可撤销。",
    "permissions.users_suffix": "用户",

    // 开发中功能
    "dev.in_development": "功能正在开发中...",
    "dev.kpi": "客服 KPI 功能正在开发中...",
    "dev.chat_report": "聊天报表功能正在开发中...",
    "dev.system_settings": "系统设置功能正在开发中...",

    // 时间设置
    "time.settings": "时间设置",
    "time.timezone": "时区",
    "time.format": "时间格式",
    "time.24hour": "24小时制",
    "time.12hour": "12小时制",
    "time.display_options": "显示选项",
    "time.show_seconds": "显示秒数",
    "time.show_date": "显示日期",
    "time.minutes_ago": "分钟前",
    "time.hours_ago": "小时前",
    "time.days_ago": "天前",
    "time.just_now": "刚刚",
    "time.last_message": "最后消息",
    "time.waiting_time": "等待时间",

    // 时区位置
    "timezone.shanghai": "上海，中国",
    "timezone.kuala_lumpur": "吉隆坡，马来西亚",
    "timezone.singapore": "新加坡",
    "timezone.tokyo": "东京，日本",
    "timezone.seoul": "首尔，韩国",
    "timezone.sydney": "悉尼，澳大利亚",
    "timezone.london": "伦敦，英国",
    "timezone.paris": "巴黎，法国",
    "timezone.berlin": "柏林，德国",
    "timezone.new_york": "纽约，美国",
    "timezone.los_angeles": "洛杉矶，美国",
    "timezone.chicago": "芝加哥，美国",

    // 优先级
    "priority.high": "高优先级",
    "priority.medium": "中优先级",
    "priority.low": "低优先级",
    "priority.high_priority": "高优先级",
    "priority.medium_priority": "中优先级",
    "priority.low_priority": "低优先级",

    // 筛选选项
    "filter.all_conversations": "全部对话",
    "filter.high_priority": "高优先级",
    "filter.medium_priority": "中优先级",
    "filter.low_priority": "低优先级",
    "filter.technical_support": "技术支持",
    "filter.sales_inquiry": "销售咨询",
    "filter.after_sales": "售后服务",
    "filter.account_filter": "账号过滤",
    "filter.workspace_a": "工作空间 A",
    "filter.workspace_b": "工作空间 B",
    "filter.select_all": "全选",
    "filter.brand_a": "品牌 A",
    "filter.brand_b": "品牌 B",
    "filter.brand_c": "品牌 C",
    "filter.brand_d": "品牌 D",
    "filter.brand_e": "品牌 E",
    "filter.brand_f": "品牌 F",

    // 所有聊天页面
    "chat.all_chats_title": "所有聊天",
    "chat.search_conversations": "搜索对话...",
    "chat.contact_info": "联系信息",
    "chat.phone": "手机",
    "chat.email": "邮箱",
    "chat.customer_tags": "客户标签",
    "chat.activity_info": "活动信息",
    "chat.join_time": "加入时间",
    "chat.last_active": "最后活跃",
    "chat.notes": "备注",
    "chat.add_tag": "添加标签",
    "chat.assign_agent": "指派客服",
    "chat.view_full_conversation": "查看完整对话",
    "chat.online": "在线",
    "chat.away": "离开",
    "chat.offline": "离线",
    "chat.send_message": "发送",
    "chat.input_message": "输入消息...",
    "chat.members": "人",
    "chat.all_chats": "所有聊天",
    "chat.search_placeholder": "搜索对话...",
    "chat.customer_service_reply": "客服回复",
    "chat.pending_conversations": "需要人工处理的对话",
    "chat.pending": "待处理",
    "chat.processing": "处理中",
    "chat.completed": "已完成",
    "chat.avg_response": "平均响应",
    "chat.assign_to_me": "分配给我",
    "chat.reply_now": "立即回复",
    "chat.view_details": "查看详情",
    "chat.assign_to_other": "分配给其他客服",
    "chat.mark_resolved": "标记为已解决",
    "chat.add_note": "添加备注",
    "chat.ai_suggestions": "AI 转接建议",
    "chat.technical_transfer": "涉及技术问题的对话建议转接给技术支持团队",
    "chat.ai_processed": "AI 已成功处理 15 个常见问题",
    "chat.time_saved": "节省人工处理时间约 45 分钟",
    "chat.no_matching_chats": "没有找到匹配的聊天",
    "chat.adjust_filters": "请调整筛选条件或搜索关键词",
    "chat.select_chat": "请选择一个聊天",
    "chat.no_messages": "暂无消息",
    "chat.private_chat": "私人聊天",
    "chat.group_chat": "群组聊天",
    "chat.channel": "频道",
    "chat.bot": "机器人",
    "chat.topic": "话题",
    "chat.system": "系统",
    "chat.no_messages_yet": "暂无消息",
    "chat.view_details_menu": "查看详情",
    "chat.mute_notifications": "静音通知",
    "chat.clear_chat": "清空聊天",
    "chat.loading_messages": "加载消息中...",
  },
  en: {
    // Common
    "common.loading": "Loading...",
    "common.search": "Search",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.view": "View",
    "common.manage": "Manage",
    "common.settings": "Settings",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.online": "Online",
    "common.offline": "Offline",
    "common.connected": "Connected",
    "common.disconnected": "Disconnected",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.changes": "Changes",
    "common.operation": "Operation",

    // System Title
    "system.title": "ChatX",
    "system.subtitle": "SaaS v1.0.0",
    "system.welcome": "Welcome back",

    // Navigation Menu
    "nav.dashboard": "Dashboard",
    "nav.customer_service": "Customer Service",
    "nav.all_chats": "All Chats",
    "nav.account_management": "Account Management",
    "nav.data_reports": "Data Reports",
    "nav.kpi": "Service KPI",
    "nav.chat_report": "Chat Report",
    "nav.system_management": "System Management",
    "nav.permissions_management": "Permissions",
    "nav.workspaces_management": "Workspace Management",
    "nav.plans_management": "Plan Management",

    // Plans Management
    "plans.title": "Plans Management",
    "plans.create": "Create Plans",
    "plans.total_plans": "Total Plans",
    "plans.active_plans": "Active Plans",
    "plans.total_subscribers": "Total Subscriber",
    "plans.total_revenue": "Total Revenue",
    "plans.search_placeholder": "Search...",
    "plans.list_title": "Plans List",
    "plans.disabled": "Disabled",
    "plans.max_workspace": "Max Workspace",
    "plans.max_account": "Max Account",
    "plans.price": "Price",
    "plans.billing_cycle": "Billing Cycle",
    "plans.monthly": "Monthly",
    "plans.quarterly": "Quarterly",
    "plans.yearly": "Yearly",
    "plans.plan_name": "Plan Name",
    "plans.plan_description": "Description",
    "plans.enter_plan_name": "Enter Plan Name...",
    "plans.enter_plan_description": "Enter Plan Description...",
    "plans.enter_plan_price": "Enter plan price",
    "plans.max_workspaces_unlimited": "Max Workspaces (0 = unlimited)",
    "plans.max_accounts_unlimited": "Max Accounts (0 = unlimited)",
    "plans.cancel": "Cancel",
    "plans.add": "Add",
    "plans.save": "Save",
    "plans.confirm_edit_title": "Confirm Edit",
    "plans.confirm_edit_message": "Are you sure you want to save changes to this plan?",
    "plans.confirm_delete_title": "Confirm Action",
    "plans.confirm_delete_message": "Are you sure you want to delete this plan?",
    "plans.confirm": "Confirm",
    "plans.edit": "Edit",
    "plans.delete": "Delete",
    "plans.plan_created_success": "Plan created successfully",
    "plans.plan_created_success_desc": "New plan has been created successfully.",
    "plans.plan_updated_success": "Plan updated successfully",
    "plans.plan_updated_success_desc": "Selected plan has been updated successfully.",
    "plans.plan_deleted_success": "Plan deleted successfully",
    "plans.plan_deleted_success_desc": "Selected plan has been deleted successfully.",
    "plans.missing_id_error": "Missing ID field.",
    "plans.missing_id_error_desc": "Cannot update a plan without an ID.",
    "plans.permission_denied": "Insufficient Permissions",
    "plans.permission_denied_desc": "You don't have permission to access this page",

    // Tooltip
    "tooltip.add_account": "Add Account",
    "tooltip.language_toggle": "Toggle Language",
    "tooltip.theme_toggle": "Toggle Theme",
    "tooltip.time_settings": "Time Settings",
    "tooltip.user_menu": "User Menu",

    // Login Page
    "login.title": "Smart Customer Service",
    "login.subtitle": "Login to access customer service management platform",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.email_placeholder": "Enter your email",
    "login.password_placeholder": "Enter your password",
    "login.button": "Login",
    "login.logging_in": "Logging in...",
    "login.demo_accounts": "Demo Accounts:",
    "login.admin_account": "Admin: admin@example.com / admin123",
    "login.manager_account": "Manager: manager@example.com / manager123",
    "login.agent_account": "Agent: agent@example.com / agent123",
    "login.error_empty": "Please enter email and password",
    "login.error_invalid": "Invalid email or password, please try again",
    "login.or_separator": "or",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.plan_id": "Plan ID",
    "dashboard.accounts": "Accounts",
    "dashboard.workspaces": "Workspaces",
    "dashboard.today_conversations": "Today's Conversations",
    "dashboard.active_users": "Active Users",
    "dashboard.ai_processing_rate": "AI Processing Rate",
    "dashboard.avg_response_time": "Avg Response Time",
    "dashboard.ai_effectiveness": "AI Effectiveness",
    "dashboard.auto_reply_success": "Auto Reply Success Rate",
    "dashboard.customer_satisfaction": "Customer Satisfaction",
    "dashboard.problem_resolution": "Problem Resolution Rate",
    "dashboard.transfer_to_human": "Transfer to Human Rate",
    "dashboard.recent_activities": "Recent Activities",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.view_conversations": "View Conversations",
    "dashboard.user_management": "User Management",
    "dashboard.data_reports": "Data Reports",
    "dashboard.ai_settings": "AI Settings",
    "dashboard.welcome_back": "Welcome back",
    "dashboard.view_reports": "View Reports",
    "dashboard.start_conversation": "Start Conversation",
    "dashboard.compared_yesterday": "vs yesterday",
    "dashboard.minutes": "minutes",
    "dashboard.auto_reply_success_rate": "Auto Reply Success Rate",
    "dashboard.customer_satisfaction_rate": "Customer Satisfaction",
    "dashboard.problem_resolution_rate": "Problem Resolution Rate",
    "dashboard.transfer_to_human_rate": "Transfer to Human Rate",
    "dashboard.new_customer_conversation": "New customer Zhang Xiaoming started conversation",
    "dashboard.ai_handled_technical": "AI successfully handled technical inquiry",
    "dashboard.service_timeout_reminder": "Service reply timeout reminder",
    "dashboard.new_user_registration": "New user registered: john@example.com",
    "dashboard.minutes_ago": "minutes ago",
    "dashboard.view_conversations_action": "View Conversations",
    "dashboard.user_management_action": "User Management",
    "dashboard.data_reports_action": "Data Reports",
    "dashboard.ai_settings_action": "AI Settings",

    // User Menu
    "user.profile": "Profile",
    "user.account_settings": "Account Settings",
    "user.logout": "Logout",
    "user.role.superadmin": "Superadmin",
    "user.role.manager": "Manager",
    "user.role.supervisor": "Supervisor",
    "user.role.agent": "Agent",
    "profile.role_readonly_description": "Role is assigned by administrator and cannot be changed",

    // Permissions
    "permission.insufficient": "Insufficient Permissions",
    "permission.no_access": "You don't have permission to access this page",
    "permission.no_access_feature": "You don't have permission to access this feature",

    // Permission category translations
    "permissions.category.User Management": "User Management",
    "permissions.category.Customer Management": "Customer Management",
    "permissions.category.System Management": "System Management",
    "permissions.category.Workspace Management": "Workspace Management",

    // Specific permission translations
    "permissions.user.create": "Create User",
    "permissions.user.edit": "Edit User",
    "permissions.user.delete": "Delete User",
    "permissions.user.view": "View User",
    "permissions.chat.manage": "Manage Chats",
    "permissions.chat.view": "View Chats",
    "permissions.chat.reply": "Reply to Chats",
    "permissions.chat.assign": "Assign Chats",
    "permissions.account.manage": "Manage Account",
    "permissions.plan.manage": "Manage Plan",
    "permissions.workspace.manage": "Manage Workspace",
    "permissions.workspace.view": "View Workspace",

    // Customer Service
    "service.title": "Customer Service",
    "service.subtitle": "Handle customer conversations and service requests",
    "service.filter": "Filter",
    "service.reply_immediately": "Reply Now",
    "service.pending_conversations_count": "Pending Conversations",
    "service.status_waiting": "Waiting",
    "service.ai_suggestions_title": "AI Transfer Suggestions",
    "service.technical_detected": "Technical conversations detected",
    "service.view_details_btn": "View Details",
    "service.view_report_btn": "View Report",
    "service.search_customer": "Search customers or conversations...",

    // Marketing Tools
    "marketing.title": "Marketing Tools",
    "marketing.subtitle": "Bulk messaging and marketing campaign management",
    "marketing.today_sent": "Today Sent",
    "marketing.reached_users": "Reached Users",
    "marketing.reply_rate": "Reply Rate",
    "marketing.conversion_rate": "Conversion Rate",
    "marketing.bulk_message": "Bulk Message",
    "marketing.bulk_description": "Send same message to multiple users",
    "marketing.create_bulk": "Create Bulk Message",
    "marketing.scheduled_send": "Scheduled Send",
    "marketing.scheduled_description": "Set message send time",
    "marketing.set_schedule": "Set Schedule",
    "marketing.customer_groups": "Customer Groups",
    "marketing.groups_description": "Manage customer groups and tags",
    "marketing.manage_groups": "Manage Groups",
    "marketing.ongoing_activities": "Ongoing Activities",
    "marketing.in_progress": "In Progress",
    "marketing.paused": "Paused",
    "marketing.send_progress": "Send Progress",
    "marketing.start_time": "Start Time",
    "marketing.estimated_completion": "Est. Completion",
    "marketing.hours_later": "hours later",
    "marketing.member_recruitment": "Member Recruitment",
    "marketing.send_statistics": "Send Statistics",
    "marketing.interaction_data": "Interaction Data",
    "marketing.open_rate": "Open Rate",
    "marketing.click_rate": "Click Rate",

    // Account Management
    "account.title": "Account Management",
    "account.subtitle": "Manage WhatsApp and Telegram account connections",
    "account.total_accounts": "Total Accounts",
    "account.connected": "Connected",
    "account.active_accounts": "Active Accounts",
    "account.today_messages": "Today's Messages",
    "account.add_account": "Add Account",
    "account.whatsapp_accounts": "WhatsApp Accounts",
    "account.telegram_accounts": "Telegram Accounts",
    "account.no_whatsapp": "No WhatsApp accounts",
    "account.no_telegram": "No Telegram accounts",
    "account.add_whatsapp": "Add WhatsApp Account",
    "account.add_telegram": "Add Telegram Account",
    "account.search_placeholder": "Search account name, phone or username...",
    "account.expand_all": "Expand All",
    "account.collapse_all": "Collapse All",
    "account.account_count": "accounts",
    "account.last_active": "Last Active",
    "account.messages": "Messages",
    "account.connection_normal": "Connection Normal",
    "account.connection_error": "Connection Error",
    "account.not_connected": "Not Connected",
    "account.status_connected": "Connected",
    "account.status_disconnected": "Disconnected",
    "account.status_error": "Connection Error",
    "account.insufficient_permission": "Insufficient Permissions",
    "account.no_permission_message": "You don't have permission to access account management",
    "account.loading_failed": "Failed to load account data",
    "account.delete_failed": "Failed to delete account",
    "account.deleted": "Account deleted",
    "account.delete_success": "Account deleted successfully",
    "account.deleting": "Deleting...",
    "account.deleting_description": "Deleting account, please wait",
    "account.toggle_failed": "Failed to toggle account status",
    "account.just_now": "just now",
    "account.minutes_ago": "minutes ago",
    "account.hours_ago": "hours ago",
    "account.days_ago": "days ago",

    // Workspace Management
    "workspace.title": "Workspace Management",
    "workspace.total_workspace": "Total Workspace",
    "workspace.total_brand": "Total Brand",
    "workspace.total_supervisor": "Total Supervisor",
    "workspace.total_agent": "Total Agent",
    "workspace.create_workspace": "Create Workspace",
    "workspace.search_placeholder": "Search...",
    "workspace.workspace_list": "Workspace List",
    "workspace.workspace_name": "Workspace Name",
    "workspace.description": "Description",
    "workspace.brands": "Brands",
    "workspace.team_members": "Team Members",
    "workspace.no_description": "No description available",
    "workspace.no_brands": "No brands assigned",
    "workspace.no_members": "No team members assigned",
    "workspace.members_count": "Team Members",
    "workspace.created_by": "Created by",
    "workspace.edit": "Edit",
    "workspace.delete": "Delete",
    "workspace.save": "Save",
    "workspace.cancel": "Cancel",
    "workspace.add": "Add",
    "workspace.confirm_delete": "Confirm Delete",
    "workspace.confirm_edit": "Confirm Edit",
    "workspace.delete_warning": "Are you sure you want to delete this workspace? This action cannot be undone.",
    "workspace.edit_warning": "Are you sure you want to edit this workspace? This action cannot be undone.",
    "workspace.create_new_brand": "Create New Brand",
    "workspace.edit_brand": "Edit Brand",
    "workspace.brand_name": "Brand Name",
    "workspace.enter_brand_name": "Enter Brand Name...",
    "workspace.create": "Create",
    "workspace.add_team_member": "Add Team Member",
    "workspace.select_subordinate": "Select Subordinate",
    "workspace.choose_user": "Choose a user",
    "workspace.no_supervisors": "No supervisors available",
    "workspace.no_agents": "No agents available",
    "workspace.select_members": "Select Members",
    "workspace.select_agent": "Select Agent",
    "workspace.display_name": "Display Name",
    "workspace.enter_workspace_name": "Enter Workspace Name...",
    "workspace.enter_workspace_description": "Enter Workspace Description...",

    // Add Account Dialog
    "dialog.add_account": "Add New Account",
    "dialog.platform_type": "Platform Type",
    "dialog.display_name": "Display Name",
    "dialog.description": "Description",
    "dialog.connection_settings": "Connection Settings",
    "dialog.please_select_connection": "Please select connection method",
    "dialog.generate_qr": "Generate QR Code",
    "dialog.phone_login": "Phone Login",
    "dialog.qr_login": "QR Login", 
    "dialog.use_phone": "Use Phone Login",
    "dialog.use_qr": "Use QR Code Login",
    "dialog.scan_qr": "Scan QR Code to Connect",
    "dialog.scan_with_app": "Please scan QR code with WhatsApp mobile app",
    "dialog.scan_with_telegram": "Please scan QR code with Telegram mobile app",
    "dialog.connection_success": "Connection Successful!",
    "dialog.click_add_to_complete": "Click Add button to complete account binding",
    "dialog.phone_number": "Phone Number",
    "dialog.phone_placeholder": "+1 555****1234",
    "dialog.send_code": "Send Code",
    "dialog.sending": "Sending...",
    "dialog.verification_code": "Verification Code",
    "dialog.code_placeholder": "Enter verification code",
    "dialog.code_sent_to": "Verification code sent to",
    "dialog.resend": "Resend",
    "dialog.verify": "Verify",
    "dialog.verifying": "Verifying...",
    "dialog.two_fa_password": "Two-Factor Password",
    "dialog.two_fa_placeholder": "Enter two-factor password",
    "dialog.two_fa_required": "Two-factor password required to complete login",
    "dialog.restart": "Restart",
    "dialog.verify_password": "Verify Password",
    "dialog.password_verifying": "Verifying...",
    "dialog.add": "Add",
    "dialog.cancel": "Cancel",
    "dialog.connecting": "Connecting",
    "dialog.loading": "Loading",
    "dialog.waiting_scan": "Waiting for QR scan",
    "dialog.connection_failed": "Connection Failed",
    "dialog.generate_qr_failed": "Failed to generate QR code",
    "dialog.regenerate": "Regenerate",
    "dialog.retry": "Retry",

    // Toast Notifications
    "toast.connection_success": "Connection Successful",
    "toast.telegram_connected": "Telegram account connected successfully!",
    "toast.whatsapp_connected": "WhatsApp account connected successfully!",
    "toast.account_added": "Account Added Successfully",
    "toast.telegram_added": "Telegram account added successfully!",
    "toast.whatsapp_added": "WhatsApp account added successfully!",
    "toast.input_error": "Input Error",
    "toast.phone_required": "Please enter phone number",
    "toast.code_required": "Please enter verification code",
    "toast.password_required": "Please enter two-factor password",
    "toast.system_error": "System Error",
    "toast.missing_tx_id": "Missing transaction ID",
    "toast.send_failed": "Send Failed",
    "toast.code_send_failed": "Failed to send verification code",
    "toast.verify_failed": "Verification Failed",
    "toast.verification_failed": "Verification failed",
    "toast.password_invalid": "Two-factor password incorrect, please try again",
    "toast.save_failed": "Save Failed",
    "toast.generate_failed": "Generation Failed",
    "toast.qr_generate_failed": "Failed to generate QR code",
    "toast.two_fa_required": "Two-Factor Required",
    "toast.two_fa_prompt": "Please enter your two-factor password",
    "toast.signup_required": "Account Registration Required",
    "toast.signup_prompt": "This phone number needs to be registered in official Telegram app first",
    "toast.missing_field" :"Login successful but warning found",
    "toast.missing_prompt": "Workspace or Brand havent selected yet. Please add on later in the edit button.",

    // Account Actions
    "account.delete_confirm_title": "Confirm Delete Account",
    "account.delete_confirm_message": "Are you sure you want to delete this account? This action cannot be undone.",
    "account.delete_confirm": "Confirm Delete",
    "account.edit_account": "Edit Account",
    "account.refresh_connection": "Refresh Connection",
    "account.expand_description": "Expand Description",
    "account.collapse_description": "Collapse Description",

    // Permissions Management
    "permissions.title": "Permissions Management",
    "permissions.subtitle": "Manage user accounts, roles and permissions",
    "permissions.create_user": "Create User",
    "permissions.total_users": "Total Users",
    "permissions.active_users": "Active Users",
    "permissions.total_roles": "Total Roles",
    "permissions.permission_items": "Permission Items",
    "permissions.user_management": "User Management",
    "permissions.role_management": "Role Management",
    "permissions.search_placeholder": "Search username or email...",
    "permissions.all_roles": "All Roles",
    "permissions.user_list": "User List",
    "permissions.current_user": "Current User",
    "permissions.disabled": "Disabled",
    "permissions.department": "Department",
    "permissions.department_placeholder": "Enter department...",
    "permissions.created": "Created",
    "permissions.last_login": "Last Login",
    "permissions.last_connected": "Last Connected",
    "permissions.never_login": "Never Logged In",
    "permissions.all_permissions": "All Permissions",
    "permissions.permissions_count": "permissions",
    "permissions.name": "Name",
    "permissions.email": "Email",
    "permissions.role": "Role",
    "permissions.merchant": "Merchant",
    "permissions.plan": "Plan",
    "permissions.password": "Password",
    "permissions.manager": "Manager",
    "permissions.reset_password": "Reset Password",
    "permissions.enter_user_name": "Enter user name",
    "permissions.enter_email": "Enter email address",
    "permissions.enter_new_password": "Enter new password",
    "permissions.no_managers_available": "No managers available",
    "permissions.role_name": "Role Name",
    "permissions.role_identifier": "Role Identifier", 
    "permissions.role_description": "Role Description",
    "permissions.enter_role_name": "Enter role name",
    "permissions.enter_role_description": "Enter role description",
    "permissions.select_role": "Select role",
    "permissions.role_list": "Role List",
    "permissions.users_count": "users",
    "permissions.permissions_count_label": "Permissions:",
    "permissions.users_count_label": "Users:",
    "permissions.edit": "Edit",
    "permissions.permissions": "Permissions",
    "permissions.permissions_configuration": "Permissions Configuration",
    "permissions.save": "Save",
    "permissions.confirm_save_changes": "Are you sure you want to save changes for",
    "permissions.confirm_update_permissions": "Are you sure you want to update this role's permissions?",
    "permissions.confirm_create_new_role": "Are you sure you want to create a new role?",
    "permissions.confirm_update_role": "Are you sure you want to update this role?",
    "permissions.confirm_delete_user": "Confirm Delete User",
    "permissions.confirm_delete_user_message": "Are you sure you want to delete user",
    "permissions.confirm_delete_user_warning": "This action cannot be undone.",
    "permissions.users_suffix": "users",

    // Development Features
    "dev.in_development": "Feature under development...",
    "dev.kpi": "Service KPI feature is under development...",
    "dev.chat_report": "Chat report feature is under development...",
    "dev.system_settings": "System settings feature is under development...",

    // Time Settings
    "time.settings": "Time Settings",
    "time.timezone": "Timezone",
    "time.format": "Time Format",
    "time.24hour": "24 Hour",
    "time.12hour": "12 Hour",
    "time.display_options": "Display Options",
    "time.show_seconds": "Show Seconds",
    "time.show_date": "Show Date",
    "time.minutes_ago": "minutes ago",
    "time.hours_ago": "hours ago",
    "time.days_ago": "days ago",
    "time.just_now": "just now",
    "time.last_message": "Last message",
    "time.waiting_time": "Waiting Time",

    // Timezone locations
    "timezone.shanghai": "Shanghai, China",
    "timezone.kuala_lumpur": "Kuala Lumpur, Malaysia",
    "timezone.singapore": "Singapore",
    "timezone.tokyo": "Tokyo, Japan",
    "timezone.seoul": "Seoul, South Korea",
    "timezone.sydney": "Sydney, Australia",
    "timezone.london": "London, United Kingdom",
    "timezone.paris": "Paris, France",
    "timezone.berlin": "Berlin, Germany",
    "timezone.new_york": "New York, United States",
    "timezone.los_angeles": "Los Angeles, United States",
    "timezone.chicago": "Chicago, United States",

    // Priority
    "priority.high": "High Priority",
    "priority.medium": "Medium Priority",
    "priority.low": "Low Priority",
    "priority.high_priority": "High Priority",
    "priority.medium_priority": "Medium Priority",
    "priority.low_priority": "Low Priority",

    // Filter options
    "filter.all_conversations": "All Conversations",
    "filter.high_priority": "High Priority",
    "filter.medium_priority": "Medium Priority",
    "filter.low_priority": "Low Priority",
    "filter.technical_support": "Technical Support",
    "filter.sales_inquiry": "Sales Inquiry",
    "filter.after_sales": "After Sales",
    "filter.account_filter": "Account Filter",
    "filter.workspace_a": "Workspace A",
    "filter.workspace_b": "Workspace B",
    "filter.select_all": "Select All",
    "filter.brand_a": "Brand A",
    "filter.brand_b": "Brand B",
    "filter.brand_c": "Brand C",
    "filter.brand_d": "Brand D",
    "filter.brand_e": "Brand E",
    "filter.brand_f": "Brand F",

    // All Chats Page
    "chat.all_chats_title": "All Chats",
    "chat.search_conversations": "Search conversations...",
    "chat.contact_info": "Contact Info",
    "chat.phone": "Phone",
    "chat.email": "Email",
    "chat.customer_tags": "Customer Tags",
    "chat.activity_info": "Activity Info",
    "chat.join_time": "Join Time",
    "chat.last_active": "Last Active",
    "chat.notes": "Notes",
    "chat.add_tag": "Add Tag",
    "chat.assign_agent": "Assign Agent",
    "chat.view_full_conversation": "View Full Conversation",
    "chat.online": "Online",
    "chat.away": "Away",
    "chat.offline": "Offline",
    "chat.send_message": "Send",
    "chat.input_message": "Type message...",
    "chat.members": "members",
    "chat.all_chats": "All Chats",
    "chat.search_placeholder": "Search conversations...",
    "chat.customer_service_reply": "Customer Service Reply",
    "chat.pending_conversations": "Conversations requiring human assistance",
    "chat.pending": "Pending",
    "chat.processing": "Processing",
    "chat.completed": "Completed",
    "chat.avg_response": "Avg Response",
    "chat.assign_to_me": "Assign to Me",
    "chat.reply_now": "Reply Now",
    "chat.view_details": "View Details",
    "chat.assign_to_other": "Assign to Other Agent",
    "chat.mark_resolved": "Mark as Resolved",
    "chat.add_note": "Add Note",
    "chat.ai_suggestions": "AI Transfer Suggestions",
    "chat.technical_transfer": "Technical conversations should be transferred to technical support team",
    "chat.ai_processed": "AI successfully processed 15 common questions",
    "chat.time_saved": "Saved approximately 45 minutes of manual processing time",
    "chat.no_matching_chats": "No matching chats found",
    "chat.adjust_filters": "Please adjust your filters or search terms",
    "chat.select_chat": "Please select a chat",
    "chat.no_messages": "No messages yet",
    "chat.private_chat": "Private Chat",
    "chat.group_chat": "Group Chat",
    "chat.channel": "Channel",
    "chat.bot": "Bot",
    "chat.topic": "Topic",
    "chat.system": "System",
    "chat.no_messages_yet": "No messages yet",
    "chat.view_details_menu": "View Details",
    "chat.mute_notifications": "Mute Notifications",
    "chat.clear_chat": "Clear Chat",
    "chat.loading_messages": "Loading messages...",

    // 语音录制相关
    "voice.recording": "Recording...",
    "voice.stop_recording": "Stop Recording",
    "voice.recording_completed": "Voice recording completed",
    "voice.delete": "Delete",
    "voice.send": "Send",
    "voice.record_voice": "Record Voice",
    "voice.voice_message": "Voice Message",
    "voice.recording_failed": "Recording Failed",
    "voice.send_failed": "Send Failed",
    "voice.sending": "Sending...",

    // 附件菜单相关
    "attachment.sticker": "Sticker",
    "attachment.document": "Document",
    "attachment.photo_video": "Photo & Video",
    "attachment.loading_failed": "Loading Failed",

    // 输入框相关
    "input.placeholder": "Type a message...",
    "input.send": "Send",
    "input.type_message": "Type a message...",

    // 系统相关
    "common.system": "System",
    "common.uploading": "Uploading...",
    "common.converting": "Converting...",
    "common.sending": "Sending...",
    "common.send_failed": "Send Failed",
    "common.upload_failed": "Upload Failed",
    "common.document": "Document",
    "common.voice_message": "Voice Message",
    "common.photo": "Photo",
    "common.video": "Video",
    "common.preparing_playback": "Preparing playback...",
    "common.downloading": "Downloading...",
    "common.loading_failed": "Loading Failed",

    // 聊天相关
    "chat.send_failed_retry": "Message send failed, please try again",

    // 测试相关
    "test.connection_test": "Connection Test",
    "test.current_status": "Current Status",
    "test.test_click": "Test Click Event",
    "test.test_api_connection": "Test API Connection",
    "test.open_console_for_logs": "Please open console to view log output",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // 从本地存储读取语言设置
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "zh" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
